
# application
sql.query.log.sql.view=true
sql.query.log.sql.full=true
quarkus.log.category."io.quarkus.config".level=DEBUG

quarkus.devservices.enabled=false
quarkus.http.root-path=/saverx/v1/admin/batch
quarkus.http.port=9005

# dashboard data request - rest client
%dev.quarkus.rest-client.aws-payer-account-summary-service.url=http://backend.opsnow.com:9085/internal/autosave/v1
quarkus.rest-client.aws-payer-account-summary-service.scope=jakarta.inject.Singleton
quarkus.rest-client.aws-payer-account-summary-service.connect-timeout=120000
quarkus.rest-client.aws-payer-account-summary-service.read-timeout=121000

# engine start - rest client
%dev.quarkus.rest-client.engine-start-api.url=http://saverx-admengine.dev.fin.opsnow.com:8080
quarkus.rest-client.engine-start-api.scope=jakarta.inject.Singleton
quarkus.rest-client.engine-start-api.connect-timeout=30000
quarkus.rest-client.engine-start-api.read-timeout=30000

%prod.aws.region=us-east-1
%dev.aws.region=ap-northeast-2

%prod.engine.cluster=prod
%dev.engine.cluster=ECS-FIN-DEV-OPSNOW
%prod.engine.service=prod
%dev.engine.service=ECSS-SAVERX-DEV-ADMENGINE


site_id=OPSNOW
analyzeTerm=7

database.bill.name=bill_new
database.cmp_admin.name=cmp_admin_dev

# datasource
# quartz
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=
quarkus.datasource.password=
quarkus.datasource.jdbc.url=

# bill
quarkus.datasource.billnew.db-kind=mysql
quarkus.datasource.billnew.username=
quarkus.datasource.billnew.password=
quarkus.datasource.billnew.reactive.url=
quarkus.datasource.billnew.reactive.max-size=50

# transaction
quarkus.transaction-manager.default-transaction-timeout=600

# logging
quarkus.log.console.async=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{1.}.%M - %L] %s%e%n
quarkus.log.console.level=DEBUG

quarkus.log.handlers=sql,error

quarkus.log.handler.file.sql.enable=true
quarkus.log.handler.file.sql.level=INFO
quarkus.log.handler.file.sql.path=logs/sql.log
quarkus.log.handler.file.sql.rotation.max-file-size=10M
quarkus.log.handler.file.sql.rotation.max-backup-index=5
quarkus.log.handler.file.sql.rotation.file-suffix=.yyyy-MM-dd
quarkus.log.handler.file.sql.format=%d (%c{.}.%M) %s%e%n
quarkus.log.handler.file.sql.filter=sql-filter


quarkus.log.handler.file.error.enable=true
quarkus.log.handler.file.error.level=ERROR
quarkus.log.handler.file.error.path=logs/error.log
quarkus.log.handler.file.error.rotation.max-file-size=10M
quarkus.log.handler.file.error.rotation.max-backup-index=5
quarkus.log.handler.file.error.rotation.file-suffix=.yyyy-MM-dd
quarkus.log.handler.file.error.format=%d (%c{.}.%M) %s%e%n


quarkus.live-reload.instrumentation=false