DATABASE_URL=mysql://rds-cost.uae.internal:3306/cmp_admin?useUnicode=true&characterEncoding=UTF-8
DATABASE_USERNAME=cmpAdminApi
DATABASE_PASSWORD=7cd8d8240c9d15e7a4b59d20575420cfD1862387329A602587DDDBC6C3194AF0