DATABASE_URL=mysql://rds-cost.uae.internal:3306/cmp_admin?useUnicode=true&characterEncoding=UTF-8
DATABASE_USERNAME=cmpAdminApi
DATABASE_PASSWORD=9c9cad22576a0dbc1b5d9aaa5f490e9b06717DED699AAF1B3F413DA1083086D6