# costadmin : dev
#DATABASE_URL=mysql://rds-cost-dev-aurora-cluster.cluster-clboygloyd3v.ap-northeast-2.rds.amazonaws.com/cmp_admin_dev?useUnicode=true&characterEncoding=UTF-8
DATABASE_URL=mysql://rds-cost.dev.internal:3306/cmp_admin_dev?useUnicode=true&characterEncoding=UTF-8
DATABASE_USERNAME=cmpAdminApi
DATABASE_PASSWORD=afa04fecd227ee8f7ae4ddf73b138c344D5B895732D35C96EC1A0D4FC7D11252